call plug#begin('~/.vim/plugged')
	Plug 'lervag/vimtex'
	Plug 'kovisoft/slimv'
	let g:tex_flavor='latex'
	let g:vimtex_view_method='zathura'
	let g:vimtex_quickfix_mode=0
	set conceallevel=1
	let g:tex_conceal='abdmg'
	let g:vimtex_compiler_latexmk = {
		\ 'build_dir' : 'pdf',
		\}

call plug#end()

let g:slimv_swank_cmd = '! tmux new -d -n REPL-SBCL "sbcl --load /home/thedvd98/.vim/plugged/slimv/slime/start-swank.lisp"'
let g:lisp_rainbow=1
"filetype plugin indent on " automatacamente eseguito da plug#end()
"syntax enable
set background=light
colorscheme solarized
syntax off
highlight Normal ctermfg=Black

set mouse=a
set autowrite
set ignorecase

" Number of visual spaces per TAB
set tabstop=4
" Number of spaces in TAB when editing
set softtabstop=4
" Number of spaces indented when reindent operations (>> and <<) are used
set shiftwidth=4

" Buffer switching
nnoremap <silent> <C-h> :bprevious<CR>
nnoremap <silent> <C-l> :bnext<CR>

"copy paste
vmap <C-S-c> "+y
vmap <C-S-V> "+p
vmap <C-c> "+y
map <C-v> "+p
vmap <C-v> "+p"
imap <C-v> <ESC>"+pi
