#! /bin/sh

urxvtd &
sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-center ~/img/walls/code_compile_run.png &
#polybar example &

bspc monitor -d α β γ δ

bspc config border_width         3
bspc config window_gap          12
#bspc config bottom_padding	20
bspc config normal_border_color "#000000"
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a qbittorent desktop='^4' state=floating follow=on
bspc rule -a qBittorent desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a librewolf desktop='^3'
bspc rule -a firefox desktop='^3'
bspc rule -a firefox-esr desktop='^3'
bspc rule -a mplayer2 desktop='^2' state=floating
bspc rule -a mpv desktop='^2' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#sun-awt-X11-XDialogPeer
