#! /bin/sh

urxvtd &
sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-center ~/img/walls/watsof.jpg &
polybar example &

bspc monitor -d α β γ δ

bspc config border_width         3
bspc config window_gap          12
bspc config bottom_padding	20
bspc config normal_border_color "#fdf6e3"
bspc config focused_border_color "#000000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#sun-awt-X11-XDialogPeer
